Validations and model specs
mohamedgamaleldin999999/fully-functioned-blog-app pull request #3
Opened 2024-01-17 00:45 UTC by mohamedgamaleldin999999

In this PR, I am trying to test my code following these requirements:

Add the following validations:
For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.
Add unit specs for all of your models' methods and validations.

2024-01-17 01:45 UTC, shahadat3669 requested changes
Hi @mohamedgamaleldin999999, 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Add Rspec test cases.
✅ Has unit tests for `User`, `Post`

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-17 01:45 UTC, shahadat3669 commented on spec/models/comment_spec.rb
> +      expect(post.comments_counter).to eq(0)
- [ ] Good job so far! However, I noticed that you added a new migration where you introduced a new column `author_id` to the comments, but according to the ER Diagram, there should be no `author_id`. I recommend removing it. 
 ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/5da4db45-e27c-4ce4-a363-250753351845). After fixing the migration, I will recommend you to rerun all test cases and fix the errors if any new problem arises.
- [ ] In this test case, you are creating a user and a post, then creating a comment. Based on your implementation, after creating a comment, the expectation should increase. However, in your test case, you are checking for 0. As per the implementation, it should be incremented. Maybe in your devise, it returns 0, but before line number 11, I recommend checking [`post.reload`](https://apidock.com/rails/ActiveRecord/Base/reload) to verify if the `comments_counter` has been updated or not. It should increment as per your test case.

2024-01-17 01:45 UTC, shahadat3669 commented on spec/models/post_spec.rb
> +    end
- [ ] This test case did not pass. Please fix the error and check all the test cases pass successfully. It says `unknown attribute 'author' for Comment.`

![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/f65374eb-e9ed-4712-a4f4-89f335511a1e)

2024-01-17 01:45 UTC, shahadat3669 commented on spec/models/like_spec.rb
> +      expect(post.liked_counter).to eq(0)
- [ ] Well! good job, but still needs some changes. It is expected to add proper unit testing for the model. Initially, in line number 8, you set `liked_counter` equal to 0, and it returns 0. This is not proper testing. Please update your test cases with meaningful assertions and cover different scenarios to ensure comprehensive testing.

2024-01-17 01:45 UTC, shahadat3669 commented on spec/models/user_spec.rb
> +      expect(user.recent_posts).to eq(user.posts.order(created_at: :desc).limit(3))
- [ ] Well! visually, your code appears to be fine, but it is not returning the expected results. You added 6 posts, so it is expected that your `recent_posts` should return the last 3 posts. After debugging, I noticed that it returns 0. Perhaps before line number 28, you can add `user.reload` as it will fetch the [attributes](https://apidock.com/rails/ActiveRecord/Base/attributes) of this object from the database again. Please fix this issue.🙏 
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/29fcc35d-6f8f-4add-8e88-0da12d0f04ab)

- [ ] Additionally, the same goes for your `recent_comments`; please check it and fix the errors. 🙏

2024-01-20 19:53 UTC, mohamedgamaleldin999999 commented
In this PR, I am trying to test my code following these requirements:

Add the following validations:
For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.
Add unit specs for all of your models' methods and validations.

Comments that I fixed:

1)
- [ ] Good job so far! However, I noticed that you added a new migration where you introduced a new column `author_id` to the comments, but according to the ER Diagram, there should be no `author_id`. I recommend removing it. 
 ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/5da4db45-e27c-4ce4-a363-250753351845). After fixing the migration, I will recommend you to rerun all test cases and fix the errors if any new problem arises.
- [ ] In this test case, you are creating a user and a post, then creating a comment. Based on your implementation, after creating a comment, the expectation should increase. However, in your test case, you are checking for 0. As per the implementation, it should be incremented. Maybe in your devise, it returns 0, but before line number 11, I recommend checking [`post.reload`](https://apidock.com/rails/ActiveRecord/Base/reload) to verify if the `comments_counter` has been updated or not. It should increment as per your test case.

2)
- [ ] Well! visually, your code appears to be fine, but it is not returning the expected results. You added 6 posts, so it is expected that your `recent_posts` should return the last 3 posts. After debugging, I noticed that it returns 0. Perhaps before line number 28, you can add `user.reload` as it will fetch the [attributes](https://apidock.com/rails/ActiveRecord/Base/attributes) of this object from the database again. Please fix this issue.🙏 
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/29fcc35d-6f8f-4add-8e88-0da12d0f04ab)

- [ ] Additionally, the same goes for your `recent_comments`; please check it and fix the errors. 🙏 

Thanks for your review

2024-01-20 21:42 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi @mohamedgamaleldin999999 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, I really appreciate the effort you put in! but there are still some which haven't been addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🌟

- ✔️Use validations for models.
- ✔️ Write unit tests for models.

## Required Changes ♻️
_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-20 21:42 UTC, abdulhamiid commented on spec/models/comment_spec.rb
> +end
As requested by the previous reviewer, please ensure that your tests are returning the expected results. 

- update_post_comments_counter
- recent_comments

Two of the tests are failing 👀.

![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/78251927/9cbdc5d7-eedb-4df4-a542-6d5b6acb03da)

Kindly check through and fix the errors. 🙏

Testing is vital for software development. It detects bugs, enhances code quality, facilitates refactoring, enables continuous integration, and reduces costs. Ultimately, it helps create better software applications that meet stakeholders' requirements. 😊

2024-01-20 21:56 UTC, mohamedgamaleldin999999 commented on spec/models/comment_spec.rb
> +end
@abdulhamiid Hello my friend. Can I reach you on slack or something to ask you more questions. Thank you I greatly appreciate it.

2024-01-20 23:05 UTC, Whoistolu commented on spec/models/comment_spec.rb
> +end
Hello, @mohamedgamaleldin999999 
I have not been able to reach you on slack and zoom

2024-01-20 23:09 UTC, mohamedgamaleldin999999 commented on spec/models/comment_spec.rb
> +end
@Whoistolu Hello my friend. thanks for trying. How can I share it with you

2024-01-20 23:11 UTC, mohamedgamaleldin999999 commented on spec/models/comment_spec.rb
> +end
@Whoistolu I just sent you a message on slack

2024-01-21 00:12 UTC, Whoistolu approved these changes
### Hi @mohamedgamaleldin999999 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-25 03:09 UTC, merged