Views
mohamedgamaleldin999999/fully-functioned-blog-app pull request #6
Opened 2024-01-25 16:31 UTC by mohamedgamaleldin999999

In this PR, I am trying to fulfil the following requirements: 

Implement the design from the sneak peek wireframes.
Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)
Note: Analyze the wireframes deeply and try to identify all the necessary elements and how a user would navigate from one page to another

Use methods that you have created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).

2024-01-25 17:33 UTC, shahadat3669 requested changes
Hi @mohamedgamaleldin999999, 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ Handled the counters nicely. 👍 
✅ `No comments` and `No posts` handle perfectly 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-25 17:33 UTC, shahadat3669 commented on app/views/users/show.html.erb
> +                        <%= post.liked_counter ? post.likes_counter : 0 %>
- [ ] Well done on your progress! However, there's a small correction needed. In this part of your code, you used `post.likes_counter`, but based on your schema, it should be `post.likes_count`. Please update your code to align with the correct attribute:

```suggestion
                        <%= post.liked_counter ? post.liked_counter : 0 %>
```

This ensures that you accurately access the likes count attribute. Keep up the good work! 🚀👍

2024-01-25 17:33 UTC, shahadat3669 commented on app/views/posts/index.html.erb
> +              <% post.recent_comments.each do |comment| %>
Well done on your progress! However, there are a couple of adjustments to consider:

- [ ] [Optional] There is an empty migration file named `20240121000917_rename_author_id_to_user_id_in_posts` in the `db/migrate` folder. If this file is unnecessary, I recommend deleting it to maintain a clean project structure.

- [ ] [Optional] I noticed a conflict between your `schema.rb` file and migration files, particularly in the `comments` table.  The `schema.rb` file indicates columns `user_id`, `post_id`, `text`, `author_id`, while the migration files suggest it should only have `user_id`, `post_id`, and `text`.To resolve this, I recommend removing the existing `schema.rb` file and regenerating it based on your current schema. This should address any conflicts. If you encounter issues, consider removing the existing schema in your local environment before regenerating it.

| migration file | Schema file|
| --- | --- |
|  ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/4054697b-7d1b-441b-b9e3-13d653bc0ef5)| ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/8cb4887c-f912-47ed-b392-c512ac522565) |

Feel free to reach out if you need further assistance or have any questions. Keep up the good work! 🚀👍

2024-01-25 17:33 UTC, shahadat3669 commented on app/views/posts/index.html.erb
> +                    <% end %>
- [ ] Good job on your progress! However, there's a slight issue with your code. In your `post#index` file, encountering difficulty finding `comment.author.name`. I recommend updating your code to resolve this issue. It seems there might be an issue with the way the `author` relationship is implemented in your model as it also not worked in the rails console.
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/84267fbd-c83f-4df6-af32-fa085d24feaa)

You can either properly implement the `author` relationship or use `comment.user.name` if that's working correctly in your model. Choose the approach that aligns with your intended model structure and ensures that you can retrieve the author's name without errors.

Keep up the good work! 🚀👍

2024-01-25 17:33 UTC, shahadat3669 commented on app/views/posts/show.html.erb
> +                            <% end %>
- [ ] Good job on your progress! However, there's a slight issue with your code. In your `post#show` file, encountering difficulty finding `comment.author.name`. I recommend updating your code to resolve this issue. It seems there might be an issue with the way the `author` relationship is implemented in your model as it also has not worked in the rails console.
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/55840999/fd0d0f87-4eb5-41eb-87f6-0e7f2976d166)

You can either properly implement the `author` relationship or use `comment.user.name` if that's working correctly in your model. Choose the approach that aligns with your intended model structure and ensures that you can retrieve the author's name without errors.

Keep up the good work! 🚀👍

2024-01-25 17:33 UTC, shahadat3669 commented on app/views/posts/index.html.erb
> +                    <% end %>
👍 Excellent progress on your project! However, to enhance the codebase, consider the following suggestion:

- [ ] **Redundancy Alert!** There's repetitive code for comments details in `post#index` , `post#show` erb file. In line with the DRY (Don't Repeat Yourself) principle, it's advisable to eliminate redundancy and maintain a clean codebase. One effective solution is to create [partials](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials). Partials are reusable templates that can streamline rendering processes and reduce code duplication. Please update your code and keep your code DRY as much as possible. 🙏 

For example:
_**_comment_list.html.erb**_
```
<!-- _comment_list.html.erb -->

<% if comments.present? && comments.length > 0 %>
  <% comments.each do |comment| %>
    <li class="list-group-item py-2">
      <span class="fw-bold">
        <%= comment.author.name %>:
      </span>
      <%= comment.text %>
    </li>
  <% end %>
<% else %>
  <li class="list-group-item">No comments</li>
<% end %>
```
**Then you can use it in different file as your wish 👍** 
```
<!-- app/views/posts/index.html.erb -->

<% if post.comments.length > 0 %>
  <%= render partial: 'shared/comment_list', locals: { comments: post.recent_comments } %>
<% else %>
  <li class="list-group-item">No comments</li>
<% end %>
```
```
<!-- app/views/posts/show.html.erb -->

<% if @post.comments.length > 0 %>
  <%= render partial: 'shared/comment_list', locals: { comments: @post.comments } %>
<% else %>
  <li class="list-group-item">No comments</li>
<% end %>
```
**_Note: Example code may not directly align with your project. Use it to gain insight and implement according to your project's needs._**

By implementing partials, you'll improve maintainability and adhere to best practices. Keep up the stellar work! 🚀👩‍💻

2024-01-25 17:33 UTC, shahadat3669 commented on app/views/users/show.html.erb
> +</div>
👍 Excellent progress on your project! However, to enhance the codebase, consider the following suggestion:

- [ ] **Redundancy Alert!** There's repetitive code for user details in `post#index` , `user#show` erb file. In line with the DRY (Don't Repeat Yourself) principle, it's advisable to eliminate redundancy and maintain a clean codebase. One effective solution is to create [partials](https://guides.rubyonrails.org/layouts_and_rendering.html#using-partials). Partials are reusable templates that can streamline rendering processes and reduce code duplication. Please update your code and keep your code DRY as much as possible. 🙏 

**_Note: I added an example in my previous comment. I recommend trying it out for yourself!_**

By implementing partials, you'll improve maintainability and adhere to best practices. Keep up the stellar work! 🚀👩‍💻

2024-01-26 03:11 UTC, Olamarx requested changes
Hi @mohamedgamaleldin999999, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media1.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"/>

 ## Highlights
- Linter free ✔️
- Good commit messages ✔️
- Gitflow ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-26 03:11 UTC, Olamarx commented on app/views/users/show.html.erb
> +                    </span>
- [ ] I noticed that the `liked_counter` still remains, probably you forgot but I will explain more. You need to know that the correct property name you created, reading from your schema file, is `likes_count` and not `liked_counter` which you defined. Kindly make amends here, please because the inconsistency in the naming would make the app break.

2024-01-26 03:11 UTC, Olamarx commented on app/views/posts/index.html.erb
> +              <% post.recent_comments.each do |comment| %>
- [ ] Just as the previous reviewer noticed, I also encountered an ActiveModel::MissingAttributeError related to the attribute author_id. This error suggests that the author_id attribute is not recognized in your Comment model.
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/86200356/3cb8195a-b758-44ed-bd2f-f077185c77f0)

Here are a few things I would recommend you check and adjust:

1. **Model Attributes:** Make sure that your `Comment` model has an attribute called `author_id`. You can do this by checking the `Comment` model file (`comment.rb`), and ensuring that there's a line like:

    ```ruby
    belongs_to :author, class_name: 'User', foreign_key: 'author_id'
    ```

   This assumes that the `Comment` model has a relationship with a `User` model through the `author_id` foreign key. Adjust the class name and foreign key as per your actual setup.

2. **Database Schema:** Check your database schema to ensure that the `comments` table has a column named `author_id`. You might need to run a migration to add this column if it's missing:

    ```bash
    rails generate migration AddAuthorIdToComments author_id:integer
    rails db:migrate
    ```

   Replace `AddAuthorIdToComments` with an appropriate name and adjust the migration file if needed.

3. **Database Associations:** Ensure that your `User` model has the corresponding association. For example:

    ```ruby
    has_many :comments, foreign_key: 'author_id'
    ```

   This assumes that a user can have many comments, and the foreign key is `author_id`. Adjust as per your actual associations.

One of these should fix the issue.

2024-01-26 03:15 UTC, mohamedgamaleldin999999 commented on app/views/posts/index.html.erb
> +              <% post.recent_comments.each do |comment| %>
@Olamarx Thanks, a lot my friend. I will work on the comments now. Would you be so kind to check with me again after I finish because the next one will be my final code review. I will appreciate it. Thanks.

2024-01-26 04:28 UTC, Davidosky007 approved these changes
Hi @mohamedgamaleldin999999 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well written PR 👍 
* No linter errors 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-26 04:28 UTC, Davidosky007 commented on app/views/users/show.html.erb
> +                </button>
## OPTIONAL
# so sorry for the mix-up by the previous CR , you were right to use `liked_counter` as that is what you have in your schema and when I used it worked , kindly look at the screenshots below and make the right adjustments so that your app works as intended 🙏 
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/52497246/3973f57e-09fd-4bcd-9a3c-533ef931ffc8)
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/52497246/7e2efbad-f73c-469c-a50d-ef5b6a1c2c7a)

![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/52497246/99fa6a05-f17d-4b8f-8a4c-98f3240284a2)

2024-01-26 04:32 UTC, mohamedgamaleldin999999 commented on app/views/users/show.html.erb
> +                </button>
@Davidosky007 
Thanks so much man I appreciate it. I really got confused. I will update it first then merge. Thanks again.

2024-01-26 04:34 UTC, merged