Add forms
mohamedgamaleldin999999/fully-functioned-blog-app pull request #7
Opened 2024-01-27 23:25 UTC by mohamedgamaleldin999999

In this PR, I am trying to fulfil these requirements:

Create a method called current_user in your ApplicationController to make current user data available to all controllers.
It will return the first user from the database.
Don't worry about proper authentication at this time. You will add it in the upcoming projects.
Create forms to perform the following functions:
Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
Allow Users to add likes to Posts.

2024-01-27 23:47 UTC, julie-ify requested changes
## Hi @mohamedgamaleldin999999,

Good job so far!

## Highlights!
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-27 23:47 UTC, julie-ify commented on app/views/posts/show.html.erb
>          </div>
- [ ] When I click the like button to like a post it raises errors. Kindly look into this and fix it.

  ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/81468675/b423a157-eb27-4226-a5a7-8f5f119a8bd8)

2024-01-27 23:47 UTC, julie-ify commented on app/views/posts/show.html.erb
> +                            <%= comment.author.name %>:
- [ ] When I create a comment, for some reason it saves, but not with the correct information, so when the app tries to load this page with an existing comment it displays error. You may need to verify how the comment is saved.

  I can see `user_id` and `author_id` within the comments schema, which is weird. You to stick to the `user_id` (based on a previous project) and ensure comments creation and display are well handled. Remember that a comment belongs to a user, not author as set up in your model.

  ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/81468675/f4a51119-7f3c-409a-8081-4213aee63bb1)

2024-01-28 00:42 UTC, mohamedgamaleldin999999 commented
In this PR, I am trying to fulfil these requirements:

Create a method called current_user in your ApplicationController to make current user data available to all controllers.
It will return the first user from the database.
Don't worry about proper authentication at this time. You will add it in the upcoming projects.
Create forms to perform the following functions:
Creates a Post on behalf of the current_user (use the method that you created in your ApplicationController).
Create a comment on behalf of the current_user (use the method that you created in your ApplicationController).
Allow Users to add likes to Posts.

The comment I worked on:
- [ ] When I create a comment, for some reason it saves, but not with the correct information, so when the app tries to load this page with an existing comment it displays error. You may need to verify how the comment is saved.

  I can see `user_id` and `author_id` within the comments schema, which is weird. You should stick to the `user_id` (based on a previous project) and ensure comments creation and display are well handled. Remember that a comment belongs to a user, not author as set up in your model.

  ![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/81468675/f4a51119-7f3c-409a-8081-4213aee63bb1)
  
  Thanks in advance for your time.

2024-01-28 01:11 UTC, Munsa1 requested changes
Hi @mohamedgamaleldin999999, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
Passing Linters :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-28 01:11 UTC, Munsa1 commented on app/controllers/likes_controller.rb
> +  end
- [ ] Because you have deleted a comment from the previous reviewer, I have to address this issue I have found and treat this as a separate review. Kindly ensure its possible for the user to add a like to a post
![image](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/81932478/5a333338-c137-456f-ba32-7faa0e6c1f4f)

ScreenCast
[cinnamon-2024-01-28T030846+0200.webm](https://github.com/mohamedgamaleldin999999/fully-functioned-blog-app/assets/81932478/81972fbd-73a4-4ae8-9a83-8b84a7cd23f3)

2024-01-28 03:41 UTC, Efiamotu-1 approved these changes
Hi @mohamedgamaleldin999999, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-01-28 03:47 UTC, merged